In [125]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.11.0-dev20221010


In [137]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [138]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [139]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.0684822 ,  0.47133267, -0.09590539,  0.68030035,  0.41559246,
         0.42947853, -0.16872948, -0.5160725 ,  0.48312765,  0.70312774]],
      dtype=float32)

In [140]:
tf.nn.softmax(predictions).numpy()

array([[0.06889819, 0.11820788, 0.06703445, 0.14568   , 0.11179921,
        0.11336249, 0.06232624, 0.04403741, 0.11961039, 0.14904374]],
      dtype=float32)

In [141]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [142]:
loss_fn(y_train[:1], predictions).numpy()

2.1771646

In [143]:
model.compile(optimizer='adam',loss=loss_fn, metrics=['accuracy'])

In [144]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2989 - accuracy: 0.9128
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1439 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1088 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0897 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0754 - accuracy: 0.9764


In [145]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0742 - accuracy: 0.9795 - 274ms/epoch - 875us/step


[0.07421489804983139, 0.9794999957084656]

In [146]:
probability_model = tf.keras.Sequential([model,tf.keras.layers.Softmax()
])

In [147]:
probability_model(x_test[:2])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[3.0756081e-07, 3.4891676e-09, 1.8241955e-05, 2.2471213e-04,
        5.1593235e-12, 5.1784093e-07, 2.5525683e-13, 9.9975556e-01,
        1.7785594e-07, 4.8369867e-07],
       [4.7663395e-08, 2.0977997e-05, 9.9997723e-01, 9.6560007e-07,
        1.6143709e-14, 6.3755954e-07, 9.1700109e-08, 4.6220669e-15,
        1.5151036e-07, 4.0390739e-11]], dtype=float32)>