In [1]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(20)
tf.add(a,b)


<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [4]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(20)
tf.subtract(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [5]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(20)
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [6]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(20)
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>